apiVersion: v1
kind: Service
metadata:
  name: gataria-backend-catalog
spec:
  type: NodePort
  selector:
    app: gataria-backend-catalog
  ports:
    - port: 80
      targetPort: 3010
      nodePort: 30010