apiVersion: v1
kind: Service
metadata:
  name: gataria-backend-images
spec:
  type: NodePort
  selector:
    app: gataria-backend-images
  ports:
    - port: 80
      targetPort: 3020
      nodePort: 30020